server:
  port: 8082

spring:
  application:
    name: uopp-telegram-bot
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

application:
  uopp-core:
    name: http://localhost:8080/

  rabbitmq:
    queue: telegram.queue